package br.com.meli.seu_imovel.repositories;

import org.springframework.stereotype.Repository;

import java.util.*;

@Repository
public class BairroRepositoryImpl implements BairroRepository{
    private static List<String> bairros = List.of(
            "Água Rasa",
            "Alto de Pinheiros",
            "Anhanguera",
            "Aricanduva",
            "Artur Alvim",
            "Barra Funda",
            "Bela Vista",
            "Belém",
            "Bom Retiro",
            "Brasilândia",
            "Butantã",
            "Cachoeirinha",
            "Cambuci",
            "Campo Belo",
            "Campo Grande",
            "Campo Limpo",
            "Cangaíba",
            "Capão Redondo",
            "Carrão",
            "Casa Verde",
            "Cidade Ademar",
            "Cidade Dutra",
            "Cidade Líder",
            "Cidade Líder",
            "Cidade Tiradentes",
            "Consolação",
            "Cursino",
            "Ermelino Matarazzo",
            "Freguesia do Ó",
            "Grajaú",
            "Guaianases",
            "Iguatemi",
            "Ipiranga",
            "Itaim Bibi",
            "Itaim Paulista",
            "Itaquera",
            "Jabaquara",
            "Jaçanã",
            "Jaguara",
            "Jaguaré",
            "Jaraguá",
            "Jardim Ângela",
            "Jardim Helena",
            "Jardim Paulista",
            "Jardim São Luís",
            "Lapa",
            "Liberdade",
            "Limão",
            "Mandaqui",
            "Marsilac",
            "Moema",
            "Mooca",
            "Morumbi",
            "Parelheiros",
            "Pari",
            "Parque do Carmo",
            "Penha",
            "Perdizes",
            "Pinheiros",
            "Ponte Rasa",
            "Raposo Tavares",
            "República",
            "Rio Pequeno",
            "Sacomã",
            "Santa Cecília",
            "Santana",
            "Santo Amaro",
            "São Domingos",
            "São Lucas",
            "São Mateus",
            "São Miguel Paulista",
            "São Rafael",
            "Sapopemba",
            "Saúde",
            "Sé",
            "Tatuapé",
            "Tremembé",
            "Tucuruvi",
            "Vila Andrade",
            "Vila Curuçá",
            "Vila Formosa",
            "Vila Guilherme",
            "Vila Jacuí",
            "Vila Leopoldina",
            "Vila Maria",
            "Vila Mariana",
            "Vila Matilde",
            "Vila Medeiros",
            "Vila Prudente",
            "Vila Sônia"
    );

    @Override
    public Optional<String> findByName(String name) {
        return bairros.stream().filter(s -> s.equals(name)).findFirst();
    }
}
